//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCanteenApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MealPlan
    {
        [Key]
        public int IdMealPlan { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdMeal { get; set; }
        public Nullable<int> IdPaid { get; set; }
        public Nullable<int> IdDay { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual Paid Paid { get; set; }
        public virtual Student Student { get; set; }
    }
}
